version:     "002--19-Sept-2021"
copyright:   "2021-2021"
description:
  This is a
  Amos GitHub Page
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "https://ferdinandamos.github.io/os212/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "TarBall"
  link:      "https://os.vlsm.org/Log/ferdinandamos.tar.bz2.txt"
- navbar:    "GitHub"
  link:      "https://github.com/ferdinandamos/"
- navbar:    "About"
  link:      "/ABOUT/"
title:       "Amos GitHub Page"
lang:        "en-US"
author:      "Ferdinand Amos P."
address:     "Depok, Jawa Barat."
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"


